<?php

namespace TwoJays\NeonApiWrapper\Enums;

enum WebhookTriggerEnum: string {
    case CREATE_ACCOUNT = 'CREATE_ACCOUNT';
    case UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
    case DELETE_ACCOUNT = 'DELETE_ACCOUNT';
    case CREATE_DONATION = 'CREATE_DONATION';
    case UPDATE_DONATION = 'UPDATE_DONATION';
    case DELETE_DONATION = 'DELETE_DONATION';
    case CREATE_MEMBERSHIP = 'CREATE_MEMBERSHIP';
    case UPDATE_MEMBERSHIP = 'UPDATE_MEMBERSHIP';
    case DELETE_MEMBERSHIP = 'DELETE_MEMBERSHIP';
    case CREATE_ACTIVITY = 'CREATE_ACTIVITY';
    case UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
    case DELETE_ACTIVITY = 'DELETE_ACTIVITY';
    case CREATE_EVENT_REGISTRATION = 'CREATE_EVENT_REGISTRATION';
    case UPDATE_EVENT_REGISTRATION = 'UPDATE_EVENT_REGISTRATION';
    case DELETE_EVENT_REGISTRATION = 'DELETE_EVENT_REGISTRATION';
    case CREATE_ORDER = 'CREATE_ORDER';
    case UPDATE_ORDER = 'UPDATE_ORDER';
    case DELETE_ORDER = 'DELETE_ORDER';
    case CREATE_MERGED_ACCOUNT = 'CREATE_MERGED_ACCOUNT';
}
